<?xml version="1.0" encoding="utf-8"?>


<!DOCTYPE carrental [
        <!ELEMENT carrental (cars|employees|rentlog)*>
        <!ELEMENT cars (car)*>
        <!ELEMENT car (id|model|year|price|color)*>
        <!ATTLIST car
                brand CDATA #REQUIRED
                class CDATA #REQUIRED
                doors CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT price (perHour|perDay)*>
        <!ELEMENT perHour (#PCDATA)>
        <!ELEMENT perDay (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT employees (employee)*>
        <!ELEMENT employee (name|surname|phone|mail|address)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT mail (#PCDATA)>
        <!ELEMENT address (city|street|postcode)*>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT postcode (#PCDATA)>
        <!ELEMENT rentlog (rental)*>
        <!ELEMENT rental (startdate|enddate|starttime|endtime)*>
        <!ATTLIST rental
                idcar CDATA #REQUIRED>
        <!ELEMENT startdate (#PCDATA)>
        <!ELEMENT enddate (#PCDATA)>
        <!ELEMENT starttime (#PCDATA)>
        <!ELEMENT endtime (#PCDATA)>
        ]>

<carrental>
    <cars>
        <car class='standard' type='sedan' brand='Toyota' doors='5'>
            <id>s1</id>
            <model>Prius</model>
            <year>2016</year>
            <price>
                <perHour>10</perHour>
                <perDay>100</perDay>
            </price>
            <color>blue</color>
        </car>
        <car class='standard' type='hatchback' brand='Honda' doors='5'>
            <id>s2</id>
            <model>Civic</model>
            <year>2010</year>
            <price>
                <perHour>8</perHour>
                <perDay>85</perDay>
            </price>
            <color>black</color>
        </car>
        <car class='standard' type='sedan' brand='Ford' doors='5'>
            <id>s3</id>
            <model>Mondeo</model>
            <year>2012</year>
            <price>
                <perHour>10</perHour>
                <perDay>100</perDay>
            </price>
            <color>grey</color>
        </car>
        <car class='premium' type='sedan' brand='Mercedes' doors='5'>
            <id>p1</id>
            <model>C-Class</model>
            <year>2016</year>
            <price>
                <perHour>15</perHour>
                <perDay>150</perDay>
            </price>
            <color>blue</color>
        </car>
        <car class='standard' type='minivan' brand='Renault' doors='5'>
            <id>s4</id>
            <model>Scenic</model>
            <year>2015</year>
            <price>
                <perHour>12</perHour>
                <perDay>120</perDay>
            </price>
            <color>white</color>
        </car>
        <car class='premium' type='suv' brand='Volvo' doors='5'>
            <id>p2</id>
            <model>XC60</model>
            <year>2017</year>
            <price>
                <perHour>18</perHour>
                <perDay>180</perDay>
            </price>
            <color>black</color>
        </car>
        <car class='standard' type='van' brand='Mercedes' doors='5'>
            <id>s5</id>
            <model>Sprinter</model>
            <year>2016</year>
            <price>
                <perHour>12</perHour>
                <perDay>120</perDay>
            </price>
            <color>yellow</color>
        </car>
        <car class='standard' type='compact' brand='Fiat' doors='3'>
            <id>s6</id>
            <model>500</model>
            <year>2016</year>
            <price>
                <perHour>12</perHour>
                <perDay>120</perDay>
            </price>
            <color>white</color>
        </car>
        <car class='premium' type='coupe' brand='Ford' doors='3'>
            <id>p3</id>
            <model>Mustang</model>
            <year>2016</year>
            <price>
                <perHour>18</perHour>
                <perDay>180</perDay>
            </price>
            <color>red</color>
        </car>
        <car class='standard' type='minivan' brand='Ford' doors='5'>
            <id>s7</id>
            <model>C-MAX</model>
            <year>2010</year>
            <price>
                <perHour>7</perHour>
                <perDay>70</perDay>
            </price>
            <color>purple</color>
        </car>
        <car class='standard' type='compact' brand='Smart' doors='3'>
            <id>s8</id>
            <model>Fortwo</model>
            <year>2016</year>
            <price>
                <perHour>10</perHour>
                <perDay>100</perDay>
            </price>
            <color>blue</color>
        </car>
        <car class='premium' type='pickup' brand='Ford' doors='3'>
            <id>p4</id>
            <model>F-150</model>
            <year>2018</year>
            <price>
                <perHour>15</perHour>
                <perDay>150</perDay>
            </price>
            <color>grey</color>
        </car>
    </cars>

    <employees>
        <employee>
            <name>Jan</name>
            <surname>Kowalski</surname>
            <phone>123456789</phone>
            <mail>jkow@gmail.com</mail>
            <address>
                <city>Gdańsk</city>   
                <street>Lęborska 11/13</street>
                <postcode>12-234</postcode>
            </address>
        </employee>
        <employee>
            <name>Marek</name>
            <surname>Nowak</surname>
            <phone>126576789</phone>
            <mail>mnow@gmail.com</mail>
            <address>
                <city>Gdańsk</city>   
                <street>Losowa 15A</street>
                <postcode>12-265</postcode>
            </address>
        </employee>
        <employee>
            <name>Joanna</name>
            <surname>Śliska</surname>
            <phone>541456789</phone>
            <mail>jslis@gmail.com</mail>
            <address>
                <city>Sopot</city>   
                <street>Niewiadoma 15/2</street>
                <postcode>25-634</postcode>
            </address>
        </employee>
        <employee>
            <name>Mateusz</name>
            <surname>Nowicki</surname>
            <phone>123456960</phone>
            <mail>mnow@gmail.com</mail>
            <address>
                <city>Gdynia</city>   
                <street>Gdańska 12B</street>
                <postcode>53-654</postcode>
            </address>
        </employee>
    </employees>

    <rentlog>
        <rental idcar='p2'>
            <startdate>2020-04-20</startdate>
            <enddate>2020-04-20</enddate>
            <starttime>18:00</starttime>
            <endtime>22:00></endtime>
        </rental>
        <rental idcar='ps2'>
            <startdate>2020-05-20</startdate>
            <enddate>2020-05-21</enddate>
            <starttime>18:00</starttime>
            <endtime>10:00></endtime>
        </rental>
        <rental idcar='s1'>
            <startdate>2020-04-10</startdate>
            <enddate>2020-04-11</enddate>
            <starttime>10:00</starttime>
            <endtime>10:00></endtime>
        </rental>
        <rental idcar='p5'>
            <startdate>2020-04-25</startdate>
            <enddate>2020-04-27</enddate>
            <starttime>18:00</starttime>
            <endtime>18:00></endtime>
        </rental>
        <rental idcar='p1'>
            <startdate>2020-04-21</startdate>
            <enddate>2020-04-21</enddate>
            <starttime>12:00</starttime>
            <endtime>18:00></endtime>
        </rental>
    </rentlog>



</carrental>